/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import model.City;
import tools.AStar;
import model.Configuration;
import tools.Event;
import tools.Node;

/**
 *
 * @author skipper
 */
public class MainJFrame extends javax.swing.JFrame{

    /**
     * Creates new form MainJFrame
     */
    //Graphic 
    int GWIDTH = 960,
        GHEIGHT = 725; 
    //Dimension screenSize = new Dimension(GWIDTH, GHEIGHT);
    private JPanel mapPanel;
    private List<City> cities = Configuration.initCities();
    private AStar map;
    public MainJFrame() {
        initComponents();
        map = Configuration.initMap(); 
        //Graphic
        this.setTitle("Algorithm Final");
        this.setSize(GWIDTH, GHEIGHT);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mapPanel = new MapJPanel(map, cities);
        jSplitPane1.setRightComponent(mapPanel);
        popCityInfo(startJComboBox);
        popCityInfo(endJComboBox);
        popPlaneType();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        startJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startJComboBox = new javax.swing.JComboBox();
        endJComboBox = new javax.swing.JComboBox();
        stormJButton = new javax.swing.JButton();
        windJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        planeTypeJComboBox = new javax.swing.JComboBox();
        breezeJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        mapJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(250);

        startJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        startJButton.setText("Start");
        startJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Departure:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Terminal:");

        startJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        endJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        endJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        stormJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stormJButton.setText("Storm");
        stormJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stormJButtonActionPerformed(evt);
            }
        });

        windJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        windJButton.setText("Strong Wind");
        windJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windJButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Type:");

        planeTypeJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        planeTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        breezeJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        breezeJButton.setText("Breeze");
        breezeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breezeJButtonActionPerformed(evt);
            }
        });

        clearJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearJButton.setText("CLear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(clearJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(planeTypeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(endJComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(breezeJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stormJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(windJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(startJComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stormJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(windJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breezeJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(planeTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout mapJPanelLayout = new javax.swing.GroupLayout(mapJPanel);
        mapJPanel.setLayout(mapJPanelLayout);
        mapJPanelLayout.setHorizontalGroup(
            mapJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        mapJPanelLayout.setVerticalGroup(
            mapJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(mapJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void popCityInfo(JComboBox combo){
        combo.removeAllItems();
        for (City c: cities) {
            combo.addItem(c);
        }
    }
    
    private void popPlaneType(){
        planeTypeJComboBox.removeAllItems();
        planeTypeJComboBox.addItem("Big Bird");
        planeTypeJComboBox.addItem("Small Bird");
    }
    
    private void startJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startJButtonActionPerformed
        City start = (City)startJComboBox.getSelectedItem();
        City end = (City)endJComboBox.getSelectedItem();
        String selectPlane = (String) planeTypeJComboBox.getSelectedItem();
        int passBound = 0;
        if(selectPlane.equals("Big Bird")){
            passBound = 2;
        }
        System.out.println("passBound:"+passBound);
        ((MapJPanel)mapPanel).startTimer(
                new Node(start.getX(), start.getY(), null), 
                new Node(end.getX(), end.getY(), null),
                passBound);
    }//GEN-LAST:event_startJButtonActionPerformed

    private void stormJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stormJButtonActionPerformed
        Event.multiCellEvent(map);
    }//GEN-LAST:event_stormJButtonActionPerformed

    private void windJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windJButtonActionPerformed
        ((MapJPanel)mapPanel).windEvent();
    }//GEN-LAST:event_windJButtonActionPerformed

    private void breezeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breezeJButtonActionPerformed
        ((MapJPanel)mapPanel).breezeEvent();
    }//GEN-LAST:event_breezeJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        Event.clearEvent(map);
    }//GEN-LAST:event_clearJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton breezeJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JComboBox endJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mapJPanel;
    private javax.swing.JComboBox planeTypeJComboBox;
    private javax.swing.JButton startJButton;
    private javax.swing.JComboBox startJComboBox;
    private javax.swing.JButton stormJButton;
    private javax.swing.JButton windJButton;
    // End of variables declaration//GEN-END:variables


    
}
